kind: pipeline
type: docker
name: integration
 
steps:

  - name: frontend-static-code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - dotnet tool list --global 
      - dotnet sonarscanner begin
          /k:"easv-devops_BmiCalculatorProject-SLA_AY_BBj_LEVvRW2O60GPZ"
          /d:sonar.host.url="http://sonar.setgo.dk:9000"  
          /d:sonar.token="$SONARSECRET"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

           

---

kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:


  - name: publish api image to docker
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: BmiCalculatorAPI-SLA/Dockerfile
      repo: sunwar01/bmi-calculator-api
      tags:
        - staging


  - name: publish frontend image to docker
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: BmiCalculatorFrontend-SLA/Dockerfile
      repo: sunwar01/bmi-calculator-frontend
      tags:
        - staging
        
        

  - name: trigger update for test
    image: curlimages/curl
    depends_on:
      - publish api image to docker
      - publish frontend image to docker
    environment:
      SONARSECRET:
        from_secret: ContaboPassword
    commands:
      - "curl --fail -X POST 'http://45.90.123.11:8080/v1/update' -H 'Authorization: Bearer "$SONARSECRET"' -H 'Content-Type: application/json' -d '{\"filters\": {\"label\": \"com.example.environment=test\"}}'"
      - sleep 10


        
  - name: update database
    image: flyway/flyway
    depends_on:
      - trigger update for test
    environment:
      SONARSECRETUSER:
        from_secret: dbUser
      SONARSECRETPASSWORD:
        from_secret: dbPassword
    commands:
      - exit 0
      - flyway migrate
          -url=jdbc:mariadb://45.90.123.12:5003/:3306/BMIDatabase
          -user="$SONARSECRETUSER"
          -password="$SONARSECRETPASSWORD"
          -locations=filesystem:./db/sql

        
        
        
  - name: performance tests
    image: grafana/k6
    depends_on:
      - update database
    commands:
     - k6 run /drone/src/Tests/spike_test.js
     - k6 run /drone/src/Tests/load_test.js
     - k6 run /drone/src/Tests/stress_test.js


  - name: end-to-end tests
    image: testcafe/testcafe
    depends_on:
      - performance tests
    commands:
      - exit 0
      - testcafe chromium:headless /drone/src/Tests/bmi_calculation_ui_test.js

        
  - name: trigger update for prod
    image: curlimages/curl
    depends_on:
      - end-to-end tests
    environment:
      SONARSECRET:
        from_secret: ContaboPassword
    commands:
      - "curl --fail -X POST 'http://45.90.123.12:8080/v1/update' -H 'Authorization: Bearer "$SONARSECRET"' -H 'Content-Type: application/json' -d '{\"filters\": {\"label\": \"com.example.environment=prod\"}}'"
      - sleep 10




 

 