kind: pipeline
type: docker
name: integration
 
steps:

  - name: frontend-static-code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - dotnet tool list --global 
      - dotnet sonarscanner begin
          /k:"easv-devops_BmiCalculatorProject-SLA_AY_BBj_LEVvRW2O60GPZ"
          /d:sonar.host.url="http://sonar.setgo.dk:9000"  
          /d:sonar.token="$SONARSECRET"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

           

---

kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:


  - name: publish api image to docker
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: BmiCalculatorAPI-SLA/Dockerfile
      repo: sunwar01/bmi-calculator-api
      tags:
        - staging


  - name: publish frontend image to docker
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: BmiCalculatorFrontend-SLA/Dockerfile
      repo: sunwar01/bmi-calculator-frontend
      tags:
        - staging
        
        

  - name: trigger update for test
    image: curlimages/curl
    commands:
      - "curl --fail -X POST 'http://http://45.90.123.11:8080/v1/update' -H 'Authorization: Bearer mytoken' -H 'Content-Type: application/json' -d '{\"filters\": {\"label\": \"com.example.environment=test\"}}'"
      - sleep 10
    depends_on:
      - publish api image to docker
      - publish frontend image to docker

        
  - name: performance tests
    image: grafana/k6
    depends_on:
      - trigger update for test
    commands:
     - k6 run /drone/src/Tests/spike_test.js

        
   - name: trigger update for prod
    image: curlimages/curl
    commands:
      - "curl --fail -X POST 'http://http://45.90.123.12:8080/v1/update' -H 'Authorization: Bearer mytoken' -H 'Content-Type: application/json' -d '{\"filters\": {\"label\": \"com.example.environment=prod\"}}'"
      - sleep 10
    depends_on:
      - performance tests



 

 